#!/usr/bin/env sh
export $(grep -v '^#' .env | xargs)
curl -so data/workspace.json --get -u "$ASSISTANT_USERNAME:$ASSISTANT_PASSWORD" https://gateway.watsonplatform.net/assistant/api/v1/workspaces/$ASSISTANT_WORKSPACE_ID/?version=$ASSISTANT_APIVERSION\&export=true